# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: app1
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/openHAB
#     targetRevision: HEAD
#     path: ./Infra/AWS/Application/
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: app1
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true 
#     automated:
#       prune: true
#       selfHeal: true
  